// <auto-generated />
using System;
using BetterGenshinImpact.Model.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BetterGenshinImpact.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250413162606_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("BetterGenshinImpact.Model.Database.TaskGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Hotkey")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("hotkey");

                    b.Property<string>("Hotkey2")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("hotkey_");

                    b.Property<DateTime?>("LastRunTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_run_time");

                    b.Property<DateTime?>("NextRunTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_run_time");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_index");

                    b.Property<string>("ScheduleExpression")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("schedule_expression");

                    b.Property<string>("ScheduleType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("schedule_type");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("task_name");

                    b.Property<string>("TaskParams")
                        .HasColumnType("TEXT")
                        .HasColumnName("task_params");

                    b.HasKey("Id");

                    b.HasIndex("OrderIndex")
                        .IsUnique();

                    b.ToTable("task_group");
                });
#pragma warning restore 612, 618
        }
    }
}
