name: I have suggestions / 我有建议
description: 分享对项目的改进建议 / Share an improvement suggestion
title: "[suggestion] "
labels:
  - 功能建议
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 提交确认 / Checklist
      description: Please confirm the following before submitting
      options:
        - label: 我已经搜索过现有 issue，确认这不是重复建议 / I have searched existing issues and confirmed this is not a duplicate suggestion
          required: true
        - label: "我已阅读过[文档](https://www.bettergi.com/doc.html)，确认文档的内容无法解决我的问题或覆盖我的建议 / I have read the [documentation](https://www.bettergi.com/doc.html) and confirmed it does not solve my problem or cover my suggestion"
          required: true
  - type: textarea
    id: suggestion
    attributes:
      label: 建议内容
      description: Suggestion
      placeholder: 请描述你的建议内容 / Describe your suggestion
    validations:
      required: true
  - type: textarea
    id: benefit
    attributes:
      label: 预期收益
      description: Expected Benefit
      placeholder: 这个建议会给用户或项目带来什么帮助？ / What benefits would this suggestion bring to users or the project?
    validations:
      required: true
