<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <Using Include="Xunit" />
    <Compile Include="../../BetterGenshinImpact/GameTask/QuickSereniteaPot/SereniteaPotWaiter.cs" Link="SereniteaPotWaiter.cs" />
    <Compile Include="../BetterGenshinImpact.UnitTest/GameTaskTests/SereniteaPotTests/SereniteaPotWaiterTests.cs" Link="SereniteaPotWaiterTests.cs" />
    <Compile Include="../../BetterGenshinImpact/GameTask/Common/GameWindowFocusWaiter.cs" Link="GameWindowFocusWaiter.cs" />
    <Compile Include="../../BetterGenshinImpact/GameTask/AutoTrackPath/MapAreaSwitchWaiter.cs" Link="MapAreaSwitchWaiter.cs" />
    <Compile Include="../BetterGenshinImpact.UnitTest/GameTaskTests/SereniteaPotTests/MapAreaSwitchWaiterTests.cs" Link="MapAreaSwitchWaiterTests.cs" />
    <Compile Include="../../BetterGenshinImpact/GameTask/QuickSereniteaPot/SereniteaPotTestSession.cs" Link="SereniteaPotTestSession.cs" />
    <Compile Include="../BetterGenshinImpact.UnitTest/GameTaskTests/SereniteaPotTests/GameWindowFocusWaiterTests.cs" Link="GameWindowFocusWaiterTests.cs" />
    <Compile Include="../BetterGenshinImpact.UnitTest/GameTaskTests/SereniteaPotTests/SereniteaPotTestSessionTests.cs" Link="SereniteaPotTestSessionTests.cs" />
  </ItemGroup>
</Project>
