using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;

namespace BetterGenshinImpact.GameTask.AutoDomain.TrainingGuide;

public sealed record TrainingGuideMaterial(string Name, string Family, int Tier, bool IsWeapon);

// 从现有 ItemV2/item.csv 提取名称、分类、星级；不依赖安装目录或识别模型的运行时状态。
public static class TrainingGuideMaterialCatalog
{
    public static IReadOnlyList<TrainingGuideMaterial> Materials { get; } = Array.AsReadOnly<TrainingGuideMaterial>([
        new("「乐园」的哲学", "「乐园」", 2, false),
        new("「乐园」的指引", "「乐园」", 1, false),
        new("「乐园」的教导", "「乐园」", 0, false),
        new("「公平」的哲学", "「公平」", 2, false),
        new("「公平」的指引", "「公平」", 1, false),
        new("「公平」的教导", "「公平」", 0, false),
        new("「勤劳」的哲学", "「勤劳」", 2, false),
        new("「勤劳」的指引", "「勤劳」", 1, false),
        new("「勤劳」的教导", "「勤劳」", 0, false),
        new("「坚忍」的哲学", "「坚忍」", 2, false),
        new("「坚忍」的指引", "「坚忍」", 1, false),
        new("「坚忍」的教导", "「坚忍」", 0, false),
        new("「天光」的哲学", "「天光」", 2, false),
        new("「天光」的指引", "「天光」", 1, false),
        new("「天光」的教导", "「天光」", 0, false),
        new("「巧思」的哲学", "「巧思」", 2, false),
        new("「巧思」的指引", "「巧思」", 1, false),
        new("「巧思」的教导", "「巧思」", 0, false),
        new("「慈爱」的哲学", "「慈爱」", 2, false),
        new("「慈爱」的指引", "「慈爱」", 1, false),
        new("「慈爱」的教导", "「慈爱」", 0, false),
        new("「抗争」的哲学", "「抗争」", 2, false),
        new("「抗争」的指引", "「抗争」", 1, false),
        new("「抗争」的教导", "「抗争」", 0, false),
        new("「月光」的哲学", "「月光」", 2, false),
        new("「月光」的指引", "「月光」", 1, false),
        new("「月光」的教导", "「月光」", 0, false),
        new("「正义」的哲学", "「正义」", 2, false),
        new("「正义」的指引", "「正义」", 1, false),
        new("「正义」的教导", "「正义」", 0, false),
        new("「浪迹」的哲学", "「浪迹」", 2, false),
        new("「浪迹」的指引", "「浪迹」", 1, false),
        new("「浪迹」的教导", "「浪迹」", 0, false),
        new("「浮世」的哲学", "「浮世」", 2, false),
        new("「浮世」的指引", "「浮世」", 1, false),
        new("「浮世」的教导", "「浮世」", 0, false),
        new("「焚燔」的哲学", "「焚燔」", 2, false),
        new("「焚燔」的指引", "「焚燔」", 1, false),
        new("「焚燔」的教导", "「焚燔」", 0, false),
        new("「秩序」的哲学", "「秩序」", 2, false),
        new("「秩序」的指引", "「秩序」", 1, false),
        new("「秩序」的教导", "「秩序」", 0, false),
        new("「笃行」的哲学", "「笃行」", 2, false),
        new("「笃行」的指引", "「笃行」", 1, false),
        new("「笃行」的教导", "「笃行」", 0, false),
        new("「繁荣」的哲学", "「繁荣」", 2, false),
        new("「繁荣」的指引", "「繁荣」", 1, false),
        new("「繁荣」的教导", "「繁荣」", 0, false),
        new("「纷争」的哲学", "「纷争」", 2, false),
        new("「纷争」的指引", "「纷争」", 1, false),
        new("「纷争」的教导", "「纷争」", 0, false),
        new("「自由」的哲学", "「自由」", 2, false),
        new("「自由」的指引", "「自由」", 1, false),
        new("「自由」的教导", "「自由」", 0, false),
        new("「荣光」的哲学", "「荣光」", 2, false),
        new("「荣光」的指引", "「荣光」", 1, false),
        new("「荣光」的教导", "「荣光」", 0, false),
        new("「角逐」的哲学", "「角逐」", 2, false),
        new("「角逐」的指引", "「角逐」", 1, false),
        new("「角逐」的教导", "「角逐」", 0, false),
        new("「诗文」的哲学", "「诗文」", 2, false),
        new("「诗文」的指引", "「诗文」", 1, false),
        new("「诗文」的教导", "「诗文」", 0, false),
        new("「诤言」的哲学", "「诤言」", 2, false),
        new("「诤言」的指引", "「诤言」", 1, false),
        new("「诤言」的教导", "「诤言」", 0, false),
        new("「风雅」的哲学", "「风雅」", 2, false),
        new("「风雅」的指引", "「风雅」", 1, false),
        new("「风雅」的教导", "「风雅」", 0, false),
        new("「黄金」的哲学", "「黄金」", 2, false),
        new("「黄金」的指引", "「黄金」", 1, false),
        new("「黄金」的教导", "「黄金」", 0, false),
        new("今昔剧画之一角", "今昔剧画", 2, true),
        new("今昔剧画之恶尉", "今昔剧画", 0, true),
        new("今昔剧画之虎啮", "今昔剧画", 1, true),
        new("今昔剧画之鬼人", "今昔剧画", 3, true),
        new("凛雪帝皇的复生", "凛雪帝皇", 0, true),
        new("凛雪帝皇的庆仪", "凛雪帝皇", 1, true),
        new("凛雪帝皇的悲恤", "凛雪帝皇", 2, true),
        new("凛雪帝皇的辞决", "凛雪帝皇", 3, true),
        new("凛风奔狼的始龀", "凛风奔狼", 0, true),
        new("凛风奔狼的怀乡", "凛风奔狼", 3, true),
        new("凛风奔狼的断牙", "凛风奔狼", 2, true),
        new("凛风奔狼的裂齿", "凛风奔狼", 1, true),
        new("奇巧秘器的模本", "奇巧秘器", 1, true),
        new("奇巧秘器的残件", "奇巧秘器", 0, true),
        new("奇巧秘器的真愿", "奇巧秘器", 3, true),
        new("奇巧秘器的继业", "奇巧秘器", 2, true),
        new("孤云寒林的光砂", "孤云寒林", 0, true),
        new("孤云寒林的圣骸", "孤云寒林", 2, true),
        new("孤云寒林的神体", "孤云寒林", 3, true),
        new("孤云寒林的辉岩", "孤云寒林", 1, true),
        new("悠古弦音的乐章", "悠古弦音", 2, true),
        new("悠古弦音的回响", "悠古弦音", 3, true),
        new("悠古弦音的断章", "悠古弦音", 1, true),
        new("悠古弦音的残章", "悠古弦音", 0, true),
        new("无垢之海的苦盏", "无垢之海", 0, true),
        new("无垢之海的酒盏", "无垢之海", 1, true),
        new("无垢之海的金杯", "无垢之海", 3, true),
        new("无垢之海的银杯", "无垢之海", 2, true),
        new("漆黑陨铁的一块", "漆黑陨铁", 3, true),
        new("漆黑陨铁的一片", "漆黑陨铁", 1, true),
        new("漆黑陨铁的一粒", "漆黑陨铁", 0, true),
        new("漆黑陨铁的一角", "漆黑陨铁", 2, true),
        new("烈日威权的余光", "烈日威权", 1, true),
        new("烈日威权的旧日", "烈日威权", 3, true),
        new("烈日威权的梦想", "烈日威权", 2, true),
        new("烈日威权的残响", "烈日威权", 0, true),
        new("狮牙斗士的枷锁", "狮牙斗士", 0, true),
        new("狮牙斗士的理想", "狮牙斗士", 3, true),
        new("狮牙斗士的铁链", "狮牙斗士", 1, true),
        new("狮牙斗士的镣铐", "狮牙斗士", 2, true),
        new("神合秘烟的启示", "神合秘烟", 3, true),
        new("神合秘烟的征兆", "神合秘烟", 2, true),
        new("神合秘烟的思绪", "神合秘烟", 0, true),
        new("神合秘烟的预感", "神合秘烟", 1, true),
        new("纯圣露滴的凝华", "纯圣露滴", 1, true),
        new("纯圣露滴的滤渣", "纯圣露滴", 0, true),
        new("纯圣露滴的真粹", "纯圣露滴", 3, true),
        new("纯圣露滴的醴泉", "纯圣露滴", 2, true),
        new("终北遗嗣的哀荣", "终北遗嗣", 0, true),
        new("终北遗嗣的煌熠", "终北遗嗣", 3, true),
        new("终北遗嗣的祷献", "终北遗嗣", 2, true),
        new("终北遗嗣的迷顽", "终北遗嗣", 1, true),
        new("绿洲花园的哀思", "绿洲花园", 2, true),
        new("绿洲花园的恩惠", "绿洲花园", 1, true),
        new("绿洲花园的真谛", "绿洲花园", 3, true),
        new("绿洲花园的追忆", "绿洲花园", 0, true),
        new("苍星军势的始动", "苍星军势", 0, true),
        new("苍星军势的征服", "苍星军势", 3, true),
        new("苍星军势的集结", "苍星军势", 1, true),
        new("苍星军势的鸣令", "苍星军势", 2, true),
        new("藏窖灵浆的恣意", "藏窖灵浆", 3, true),
        new("藏窖灵浆的斟酌", "藏窖灵浆", 0, true),
        new("藏窖灵浆的酣畅", "藏窖灵浆", 2, true),
        new("藏窖灵浆的酩酊", "藏窖灵浆", 1, true),
        new("谧林涓露的金符", "谧林涓露", 3, true),
        new("谧林涓露的铁符", "谧林涓露", 1, true),
        new("谧林涓露的铜符", "谧林涓露", 0, true),
        new("谧林涓露的银符", "谧林涓露", 2, true),
        new("谵妄圣主的余哀", "谵妄圣主", 1, true),
        new("谵妄圣主的容光", "谵妄圣主", 2, true),
        new("谵妄圣主的朽败", "谵妄圣主", 0, true),
        new("谵妄圣主的神面", "谵妄圣主", 3, true),
        new("贡祭炽心的决绝", "贡祭炽心", 2, true),
        new("贡祭炽心的惶恐", "贡祭炽心", 0, true),
        new("贡祭炽心的荣膺", "贡祭炽心", 3, true),
        new("贡祭炽心的踌躇", "贡祭炽心", 1, true),
        new("远海夷地的玉枝", "远海夷地", 1, true),
        new("远海夷地的琼枝", "远海夷地", 2, true),
        new("远海夷地的瑚枝", "远海夷地", 0, true),
        new("远海夷地的金枝", "远海夷地", 3, true),
        new("长夜燧火的余烬", "长夜燧火", 0, true),
        new("长夜燧火的明焰", "长夜燧火", 2, true),
        new("长夜燧火的残照", "长夜燧火", 1, true),
        new("长夜燧火的烈辉", "长夜燧火", 3, true),
        new("雾海云间的汞丹", "雾海云间", 1, true),
        new("雾海云间的转还", "雾海云间", 3, true),
        new("雾海云间的金丹", "雾海云间", 2, true),
        new("雾海云间的铅丹", "雾海云间", 0, true),
        new("高塔孤王的断片", "高塔孤王", 2, true),
        new("高塔孤王的残垣", "高塔孤王", 1, true),
        new("高塔孤王的破瓦", "高塔孤王", 0, true),
        new("高塔孤王的碎梦", "高塔孤王", 3, true),
        new("鸣神御灵的亲爱", "鸣神御灵", 2, true),
        new("鸣神御灵的勇武", "鸣神御灵", 3, true),
        new("鸣神御灵的明惠", "鸣神御灵", 0, true),
        new("鸣神御灵的欢喜", "鸣神御灵", 1, true),
    ]);

    public static string Normalize(string text) => Regex.Replace(text, @"\s+", "")
        .Replace('“', '「').Replace('”', '」').Replace("凛雪帝皇的辞诀", "凛雪帝皇的辞决")
        .Replace("「净言」", "「诤言」");

    public static TrainingGuideMaterial? Find(string text)
    {
        var normalized = Normalize(text);
        var matches = Materials.Where(m => normalized == Normalize(m.Name)).ToArray();
        return matches.Length == 1 ? matches[0] : null;
    }

    // 周日/限时全开放时按等级排列，每一级内有三个家族：三六日、二五日、一四日。
    // familyPosition 是“同一级内”的零基序号，不是整条材料列表的卡片序号。
    // 不可假设同一家族的所有等级连续出现；扫描结果必须按材料名称归入家族和等级。
    public static int SelectionIndex(int familyPosition) => familyPosition is >= 0 and <= 2
        ? 3 - familyPosition : throw new ArgumentOutOfRangeException(nameof(familyPosition));
}

