using BetterGenshinImpact.Core.Config;
using BetterGenshinImpact.Core.Recognition;
using BetterGenshinImpact.Helpers.Extensions;
using BetterGenshinImpact.Service;
using BetterGenshinImpact.Service.Interface;
using BetterGenshinImpact.View.Behavior;
using BetterGenshinImpact.View.Windows;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Microsoft.Extensions.Logging;
using Ookii.Dialogs.Wpf;
using OpenCvSharp;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Windows;
using System.Windows.Media.Imaging;
using CvRect = OpenCvSharp.Rect;

namespace BetterGenshinImpact.ViewModel.Windows;

public partial class RecognitionTemplateEditorViewModel : ViewModel, IDisposable
{
    private const int MaxRecentOutputPathCount = 10;

    private readonly Mat _screenshot;
    private readonly RecognitionTemplateAssetService _assetService;
    private readonly DevConfig _devConfig;
    private readonly ILogger<RecognitionTemplateEditorViewModel> _logger = App.GetLogger<RecognitionTemplateEditorViewModel>();
    private bool _disposed;
    private string _lastAutoGeneratedObjectName = "";

    public event Action? RequestClose;

    public IReadOnlyList<TemplateMatchModes> TemplateMatchModeItems { get; } = Enum.GetValues<TemplateMatchModes>();

    public IReadOnlyList<SearchAnchorMode> SearchAnchorModeItems { get; } = Enum.GetValues<SearchAnchorMode>();

    /// <summary>
    /// 最近使用的 Recognition.json 输出文件，按最近使用顺序排列，最多 10 条。
    /// </summary>
    public ObservableCollection<string> RecentRecognitionJsonPaths { get; } = [];

    /// <summary>
    /// 最近使用的 Assets 输出文件夹，按最近使用顺序排列，最多 10 条。
    /// </summary>
    public ObservableCollection<string> RecentAssetsRootPaths { get; } = [];

    public int CanvasWidth => _screenshot.Width;

    public int CanvasHeight => _screenshot.Height;

    public string ReferenceSizeText => $"{CanvasWidth} x {CanvasHeight}";

    public string OutputImagePath => RecognitionTemplateAssetService.GetImageOutputPath(AssetsRootPath, TemplateFileNameWithExtension);

    public string OutputImageDisplayPath => GetDisplayPath(OutputImagePath);

    private string TemplateFileNameWithExtension => string.IsNullOrWhiteSpace(TemplateFileName)
        ? ""
        : ConvertToSnakeCase(TemplateFileName) + ".png";

    [ObservableProperty]
    private WriteableBitmap _screenshotImage;

    [ObservableProperty]
    private WriteableBitmap? _croppedPreviewImage;

    [ObservableProperty]
    private string _recognitionJsonPath;

    [ObservableProperty]
    private string _assetsRootPath;

    [ObservableProperty]
    private string _objectName = "";

    [ObservableProperty]
    private string _templateFileName = "";

    [ObservableProperty]
    private int _selectionX;

    [ObservableProperty]
    private int _selectionY;

    [ObservableProperty]
    private int _selectionWidth;

    [ObservableProperty]
    private int _selectionHeight;

    [ObservableProperty]
    private double _threshold = RecognitionTemplateDraft.DefaultThreshold;

    [ObservableProperty]
    private TemplateMatchModes _templateMatchMode = RecognitionTemplateDraft.DefaultTemplateMatchMode;

    [ObservableProperty]
    private bool _use3Channels;

    [ObservableProperty]
    private bool _useMask;

    [ObservableProperty]
    private string _maskColor = RecognitionTemplateDraft.DefaultMaskColor;

    [ObservableProperty]
    private bool _useBinaryMatch;

    [ObservableProperty]
    private int _binaryThreshold = RecognitionTemplateDraft.DefaultBinaryThreshold;

    [ObservableProperty]
    private int _maxMatchCount = RecognitionTemplateDraft.DefaultMaxMatchCount;

    [ObservableProperty]
    private bool _drawOnWindow;

    [ObservableProperty]
    private SearchAnchorMode _searchAnchorMode = RecognitionTemplateDraft.DefaultSearchAnchorMode;

    /// <summary>
    /// 是否输出独立的 search.box；关闭时基础搜索框回退为模板框。
    /// </summary>
    [ObservableProperty]
    private bool _useCustomSearchBox;

    /// <summary>
    /// 当前由画布 Behavior 修改的矩形类型。
    /// </summary>
    [ObservableProperty]
    private TemplateImageSelectionTarget _selectionTarget = TemplateImageSelectionTarget.Template;

    /// <summary>
    /// 独立搜索框在参考画布坐标系中的左上角 X 坐标。
    /// </summary>
    [ObservableProperty]
    private int _searchBoxX;

    /// <summary>
    /// 独立搜索框在参考画布坐标系中的左上角 Y 坐标。
    /// </summary>
    [ObservableProperty]
    private int _searchBoxY;

    /// <summary>独立搜索框在参考画布坐标系中的宽度。</summary>
    [ObservableProperty]
    private int _searchBoxWidth;

    /// <summary>独立搜索框在参考画布坐标系中的高度。</summary>
    [ObservableProperty]
    private int _searchBoxHeight;

    [ObservableProperty]
    private int _searchExpandWidth = RecognitionTemplateDraft.DefaultSearchExpand;

    [ObservableProperty]
    private int _searchExpandHeight = RecognitionTemplateDraft.DefaultSearchExpand;

    /// <summary>
    /// 是否输出 search.expandPercent；关闭时仅输出像素 expand 模式。
    /// </summary>
    [ObservableProperty]
    private bool _usePercentSearchExpand;

    /// <summary>
    /// 左侧搜索扩展比例，直接使用小数表示，例如 0.05 表示当前截图宽度的 5%。
    /// </summary>
    [ObservableProperty]
    private double _searchExpandLeftPercent;

    /// <summary>
    /// 上侧搜索扩展比例，直接使用小数表示，例如 0.05 表示当前截图高度的 5%。
    /// </summary>
    [ObservableProperty]
    private double _searchExpandTopPercent;

    /// <summary>
    /// 右侧搜索扩展比例，直接使用小数表示，例如 0.05 表示当前截图宽度的 5%。
    /// </summary>
    [ObservableProperty]
    private double _searchExpandRightPercent;

    /// <summary>
    /// 下侧搜索扩展比例，直接使用小数表示，例如 0.05 表示当前截图高度的 5%。
    /// </summary>
    [ObservableProperty]
    private double _searchExpandBottomPercent;

    private int _effectiveSearchX;
    private int _effectiveSearchY;
    private int _effectiveSearchWidth;
    private int _effectiveSearchHeight;
    private bool _hasEffectiveSearchPreview;

    [ObservableProperty]
    private double _zoomScale = 0.5;

    [ObservableProperty]
    private int _fitRequestToken;

    public bool IsEditingTemplateBox
    {
        get => SelectionTarget == TemplateImageSelectionTarget.Template;
        set
        {
            if (value)
            {
                SelectionTarget = TemplateImageSelectionTarget.Template;
            }
        }
    }

    public bool IsEditingSearchBox
    {
        get => SelectionTarget == TemplateImageSelectionTarget.SearchBox;
        set
        {
            if (value && UseCustomSearchBox)
            {
                SelectionTarget = TemplateImageSelectionTarget.SearchBox;
            }
        }
    }

    public bool UsePixelSearchExpand
    {
        get => !UsePercentSearchExpand;
        set
        {
            if (value)
            {
                UsePercentSearchExpand = false;
            }
        }
    }

    public int EffectiveSearchX
    {
        get => _effectiveSearchX;
        private set => SetProperty(ref _effectiveSearchX, value);
    }

    public int EffectiveSearchY
    {
        get => _effectiveSearchY;
        private set => SetProperty(ref _effectiveSearchY, value);
    }

    public int EffectiveSearchWidth
    {
        get => _effectiveSearchWidth;
        private set => SetProperty(ref _effectiveSearchWidth, value);
    }

    public int EffectiveSearchHeight
    {
        get => _effectiveSearchHeight;
        private set => SetProperty(ref _effectiveSearchHeight, value);
    }

    public bool HasEffectiveSearchPreview
    {
        get => _hasEffectiveSearchPreview;
        private set => SetProperty(ref _hasEffectiveSearchPreview, value);
    }

    public RecognitionTemplateEditorViewModel(
        Mat screenshot,
        RecognitionTemplateAssetService assetService,
        IConfigService configService,
        string initialTemplateName = "")
    {
        _screenshot = screenshot ?? throw new ArgumentNullException(nameof(screenshot));
        _assetService = assetService;
        _devConfig = configService.Get().DevConfig;
        _recognitionJsonPath = _devConfig.RecognitionJsonPath;
        _assetsRootPath = _devConfig.RecognitionAssetsRootPath;
        LoadRecentPaths(RecentRecognitionJsonPaths, _recognitionJsonPath, _devConfig.RecognitionJsonPathHistory);
        LoadRecentPaths(RecentAssetsRootPaths, _assetsRootPath, _devConfig.RecognitionAssetsRootPathHistory);
        _screenshotImage = screenshot.ToWriteableBitmap();
        // 百分比模式默认保持与旧版 10px 扩展相同的参考画布预览效果，运行时再随截图宽高响应式缩放。
        _searchExpandLeftPercent = RecognitionTemplateDraft.DefaultSearchExpand / (double)Math.Max(1, CanvasWidth);
        _searchExpandRightPercent = _searchExpandLeftPercent;
        _searchExpandTopPercent = RecognitionTemplateDraft.DefaultSearchExpand / (double)Math.Max(1, CanvasHeight);
        _searchExpandBottomPercent = _searchExpandTopPercent;
        if (!string.IsNullOrWhiteSpace(initialTemplateName))
        {
            TemplateFileName = initialTemplateName;
        }
    }

    [RelayCommand]
    private void BrowseRecognitionJson()
    {
        var dialog = new VistaSaveFileDialog
        {
            Title = "选择或创建 Recognition.json",
            Filter = "Recognition JSON (*.json)|*.json|所有文件 (*.*)|*.*",
            DefaultExt = ".json",
            AddExtension = true,
            OverwritePrompt = false,
            FileName = "Recognition.json"
        };

        TrySetDialogInitialPath(dialog, RecognitionJsonPath);
        if (dialog.ShowDialog(GetActiveWindow()) != true)
        {
            return;
        }

        RecognitionJsonPath = dialog.FileName;
        RememberRecognitionJsonPath(dialog.FileName);
        if (string.IsNullOrWhiteSpace(AssetsRootPath))
        {
            AssetsRootPath = Path.GetDirectoryName(dialog.FileName) ?? "";
            RememberAssetsRootPath(AssetsRootPath);
        }
    }

    [RelayCommand]
    private void BrowseAssetsRoot()
    {
        var dialog = new VistaFolderBrowserDialog
        {
            Description = "选择输出文件夹（Recognition.json 写入此目录，图片写入 1920x1080 子目录）",
            UseDescriptionForTitle = true,
            SelectedPath = Directory.Exists(AssetsRootPath) ? AssetsRootPath : ""
        };
        if (dialog.ShowDialog(GetActiveWindow()) != true)
        {
            return;
        }

        AssetsRootPath = dialog.SelectedPath;
        RecognitionJsonPath = Path.Combine(dialog.SelectedPath, "Recognition.json");
        RememberAssetsRootPath(dialog.SelectedPath);
        RememberRecognitionJsonPath(RecognitionJsonPath);
    }

    [RelayCommand]
    private void FitImage()
    {
        FitRequestToken++;
    }

    [RelayCommand]
    private void Save()
    {
        try
        {
            NormalizeTemplateFileName();
            var draft = new RecognitionTemplateDraft
            {
                JsonPath = RecognitionJsonPath,
                AssetsRootPath = AssetsRootPath,
                ObjectName = ObjectName,
                TemplateFileName = TemplateFileNameWithExtension,
                Selection = new CvRect(SelectionX, SelectionY, SelectionWidth, SelectionHeight),
                ReferenceWidth = CanvasWidth,
                ReferenceHeight = CanvasHeight,
                Threshold = Threshold,
                TemplateMatchMode = TemplateMatchMode,
                Use3Channels = Use3Channels,
                UseMask = UseMask,
                MaskColor = MaskColor,
                UseBinaryMatch = UseBinaryMatch,
                BinaryThreshold = BinaryThreshold,
                MaxMatchCount = MaxMatchCount,
                DrawOnWindow = DrawOnWindow,
                SearchAnchorMode = SearchAnchorMode,
                ReferenceSearchBox = UseCustomSearchBox
                    ? new CvRect(SearchBoxX, SearchBoxY, SearchBoxWidth, SearchBoxHeight)
                    : null,
                SearchExpandWidth = SearchExpandWidth,
                SearchExpandHeight = SearchExpandHeight,
                SearchExpandPercent = UsePercentSearchExpand
                    ? new SearchExpandRatio(
                        SearchExpandLeftPercent,
                        SearchExpandTopPercent,
                        SearchExpandRightPercent,
                        SearchExpandBottomPercent)
                    : null
            };

            var plan = _assetService.Prepare(draft);
            if (plan.Conflicts.Count > 0)
            {
                var conflictText = string.Join(Environment.NewLine, plan.Conflicts.Select(conflict => $"• {conflict}"));
                var result = ThemedMessageBox.Show(
                    $"检测到以下冲突：{Environment.NewLine}{Environment.NewLine}{conflictText}{Environment.NewLine}{Environment.NewLine}是否覆盖并继续保存？",
                    "确认覆盖模板素材",
                    MessageBoxButton.YesNo,
                    ThemedMessageBox.MessageBoxIcon.Warning,
                    MessageBoxResult.No,
                    GetActiveWindow());
                if (result != MessageBoxResult.Yes)
                {
                    return;
                }
            }

            _assetService.Commit(plan, _screenshot);
            RememberRecognitionJsonPath(plan.JsonPath);
            RememberAssetsRootPath(Path.GetFullPath(AssetsRootPath.Trim()));

            ThemedMessageBox.Show(
                $"模板素材已保存。{Environment.NewLine}{Environment.NewLine}配置：{plan.JsonPath}{Environment.NewLine}图片：{plan.ImagePath}",
                "保存成功",
                MessageBoxButton.OK,
                ThemedMessageBox.MessageBoxIcon.Success,
                MessageBoxResult.OK,
                GetActiveWindow());
            RequestClose?.Invoke();
        }
        catch (ArgumentException ex)
        {
            ShowWarning(ex.Message);
        }
        catch (InvalidOperationException ex)
        {
            ShowWarning(ex.Message);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "保存 Recognition 模板素材失败");
            ThemedMessageBox.Show(
                $"保存 Recognition 模板素材失败：{ex.Message}",
                "保存失败",
                MessageBoxButton.OK,
                ThemedMessageBox.MessageBoxIcon.Error,
                MessageBoxResult.OK,
                GetActiveWindow());
        }
    }

    [RelayCommand]
    private void Cancel()
    {
        RequestClose?.Invoke();
    }

    [RelayCommand]
    private void NormalizeTemplateFileName()
    {
        var normalizedName = ConvertToSnakeCase(TemplateFileName);
        TemplateFileName = normalizedName;
    }

    partial void OnRecognitionJsonPathChanged(string value)
    {
        OnPropertyChanged(nameof(OutputImagePath));
    }

    partial void OnAssetsRootPathChanged(string value)
    {
        OnPropertyChanged(nameof(OutputImagePath));
        OnPropertyChanged(nameof(OutputImageDisplayPath));
    }

    /// <summary>
    /// 加载持久化的最近路径，并将旧版单值配置放在首位完成向后兼容迁移。
    /// 空路径会被忽略，Windows 路径按不区分大小写的方式去重。
    /// </summary>
    private static void LoadRecentPaths(
        ObservableCollection<string> target,
        string currentPath,
        IEnumerable<string>? persistedPaths)
    {
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        IEnumerable<string> candidates = string.IsNullOrWhiteSpace(currentPath)
            ? persistedPaths ?? []
            : new[] { currentPath }.Concat(persistedPaths ?? []);

        foreach (var candidate in candidates)
        {
            var path = candidate?.Trim();
            if (string.IsNullOrWhiteSpace(path) || !seen.Add(path))
            {
                continue;
            }

            target.Add(path);
            if (target.Count >= MaxRecentOutputPathCount)
            {
                break;
            }
        }
    }

    private void RememberRecognitionJsonPath(string path)
    {
        if (string.IsNullOrWhiteSpace(path))
        {
            return;
        }

        var normalizedPath = path.Trim();
        _devConfig.RecognitionJsonPath = normalizedPath;
        RememberRecentPath(
            normalizedPath,
            RecentRecognitionJsonPaths,
            recentPaths => _devConfig.RecognitionJsonPathHistory = recentPaths);
    }

    private void RememberAssetsRootPath(string path)
    {
        if (string.IsNullOrWhiteSpace(path))
        {
            return;
        }

        var normalizedPath = path.Trim();
        _devConfig.RecognitionAssetsRootPath = normalizedPath;
        RememberRecentPath(
            normalizedPath,
            RecentAssetsRootPaths,
            recentPaths => _devConfig.RecognitionAssetsRootPathHistory = recentPaths);
    }

    /// <summary>
    /// 将路径移动到最近记录首位，按 Windows 路径规则去重并截断到 10 条。
    /// 每次都向 DevConfig 赋新集合，以触发当前配置服务的 PropertyChanged 持久化机制。
    /// </summary>
    private static void RememberRecentPath(
        string path,
        ObservableCollection<string> target,
        Action<List<string>> persist)
    {
        var normalizedPath = path.Trim();
        if (string.IsNullOrWhiteSpace(normalizedPath))
        {
            return;
        }

        var existing = target.FirstOrDefault(item =>
            string.Equals(item, normalizedPath, StringComparison.OrdinalIgnoreCase));
        if (existing != null)
        {
            target.Remove(existing);
        }

        target.Insert(0, normalizedPath);
        while (target.Count > MaxRecentOutputPathCount)
        {
            target.RemoveAt(target.Count - 1);
        }

        persist([.. target]);
    }

    partial void OnTemplateFileNameChanged(string value)
    {
        OnPropertyChanged(nameof(OutputImagePath));
        OnPropertyChanged(nameof(OutputImageDisplayPath));
        UpdateAutoGeneratedObjectName(value);
    }

    partial void OnSelectionXChanged(int value) => OnTemplateSelectionChanged();

    partial void OnSelectionYChanged(int value) => OnTemplateSelectionChanged();

    partial void OnSelectionWidthChanged(int value) => OnTemplateSelectionChanged();

    partial void OnSelectionHeightChanged(int value) => OnTemplateSelectionChanged();

    partial void OnUseCustomSearchBoxChanged(bool value)
    {
        if (value)
        {
            if (HasValidTemplateSelection())
            {
                CopyTemplateSelectionToSearchBox();
            }

            SelectionTarget = TemplateImageSelectionTarget.SearchBox;
        }
        else
        {
            SelectionTarget = TemplateImageSelectionTarget.Template;
        }

        OnPropertyChanged(nameof(IsEditingSearchBox));
        UpdateEffectiveSearchPreview();
    }

    partial void OnSelectionTargetChanged(TemplateImageSelectionTarget value)
    {
        if (value == TemplateImageSelectionTarget.SearchBox && !UseCustomSearchBox)
        {
            SelectionTarget = TemplateImageSelectionTarget.Template;
            return;
        }

        OnPropertyChanged(nameof(IsEditingTemplateBox));
        OnPropertyChanged(nameof(IsEditingSearchBox));
    }

    partial void OnSearchBoxXChanged(int value) => UpdateEffectiveSearchPreview();

    partial void OnSearchBoxYChanged(int value) => UpdateEffectiveSearchPreview();

    partial void OnSearchBoxWidthChanged(int value) => UpdateEffectiveSearchPreview();

    partial void OnSearchBoxHeightChanged(int value) => UpdateEffectiveSearchPreview();

    partial void OnSearchExpandWidthChanged(int value) => UpdateEffectiveSearchPreview();

    partial void OnSearchExpandHeightChanged(int value) => UpdateEffectiveSearchPreview();

    partial void OnUsePercentSearchExpandChanged(bool value)
    {
        OnPropertyChanged(nameof(UsePixelSearchExpand));
        UpdateEffectiveSearchPreview();
    }

    partial void OnSearchExpandLeftPercentChanged(double value) => UpdateEffectiveSearchPreview();

    partial void OnSearchExpandTopPercentChanged(double value) => UpdateEffectiveSearchPreview();

    partial void OnSearchExpandRightPercentChanged(double value) => UpdateEffectiveSearchPreview();

    partial void OnSearchExpandBottomPercentChanged(double value) => UpdateEffectiveSearchPreview();

    private void OnTemplateSelectionChanged()
    {
        UpdateCroppedPreview();
        UpdateEffectiveSearchPreview();
    }

    private void UpdateCroppedPreview()
    {
        var selection = new CvRect(SelectionX, SelectionY, SelectionWidth, SelectionHeight);
        if (selection.Width <= 0 || selection.Height <= 0
            || selection.X < 0 || selection.Y < 0
            || selection.Right > CanvasWidth || selection.Bottom > CanvasHeight)
        {
            CroppedPreviewImage = null;
            return;
        }

        using var cropped = new Mat(_screenshot, selection);
        CroppedPreviewImage = cropped.ToWriteableBitmap();
    }

    private bool HasValidTemplateSelection()
    {
        return SelectionWidth > 0 && SelectionHeight > 0;
    }

    private void CopyTemplateSelectionToSearchBox()
    {
        SearchBoxX = SelectionX;
        SearchBoxY = SelectionY;
        SearchBoxWidth = SelectionWidth;
        SearchBoxHeight = SelectionHeight;
    }

    /// <summary>
    /// 在参考截图上预览最终生效的搜索范围。
    /// 百分比模式按画布宽高计算四边并优先于像素模式，计算规则与运行时保持一致。
    /// </summary>
    private void UpdateEffectiveSearchPreview()
    {
        var baseRect = UseCustomSearchBox
            ? new CvRect(SearchBoxX, SearchBoxY, SearchBoxWidth, SearchBoxHeight)
            : new CvRect(SelectionX, SelectionY, SelectionWidth, SelectionHeight);
        if (baseRect.Width <= 0 || baseRect.Height <= 0)
        {
            HasEffectiveSearchPreview = false;
            EffectiveSearchX = EffectiveSearchY = EffectiveSearchWidth = EffectiveSearchHeight = 0;
            return;
        }

        double left;
        double top;
        double right;
        double bottom;
        if (UsePercentSearchExpand)
        {
            var ratio = new SearchExpandRatio(
                SearchExpandLeftPercent,
                SearchExpandTopPercent,
                SearchExpandRightPercent,
                SearchExpandBottomPercent);
            if (!ratio.IsValid)
            {
                HasEffectiveSearchPreview = false;
                return;
            }

            left = CanvasWidth * ratio.Left;
            top = CanvasHeight * ratio.Top;
            right = CanvasWidth * ratio.Right;
            bottom = CanvasHeight * ratio.Bottom;
        }
        else
        {
            left = right = Math.Max(0, SearchExpandWidth);
            top = bottom = Math.Max(0, SearchExpandHeight);
        }

        var x1 = (int)Math.Round(Math.Clamp(baseRect.Left - left, 0d, CanvasWidth));
        var y1 = (int)Math.Round(Math.Clamp(baseRect.Top - top, 0d, CanvasHeight));
        var x2 = (int)Math.Round(Math.Clamp(baseRect.Right + right, 0d, CanvasWidth));
        var y2 = (int)Math.Round(Math.Clamp(baseRect.Bottom + bottom, 0d, CanvasHeight));
        EffectiveSearchX = x1;
        EffectiveSearchY = y1;
        EffectiveSearchWidth = Math.Max(0, x2 - x1);
        EffectiveSearchHeight = Math.Max(0, y2 - y1);
        HasEffectiveSearchPreview = EffectiveSearchWidth > 0 && EffectiveSearchHeight > 0;
    }

    private void UpdateAutoGeneratedObjectName(string templateFileName)
    {
        var generatedObjectName = ConvertToPascalCase(templateFileName);
        if (string.IsNullOrWhiteSpace(ObjectName)
            || string.Equals(ObjectName, _lastAutoGeneratedObjectName, StringComparison.Ordinal))
        {
            ObjectName = generatedObjectName;
        }

        _lastAutoGeneratedObjectName = generatedObjectName;
    }

    private static string ConvertToSnakeCase(string value)
    {
        var normalized = value.Trim();
        if (normalized.EndsWith(".png", StringComparison.OrdinalIgnoreCase))
        {
            normalized = normalized[..^4];
        }

        // 兼容 PascalCase、camelCase、连续大写缩写以及空格/连字符等分隔符。
        normalized = Regex.Replace(normalized, @"([A-Z]+)([A-Z][a-z])", "$1_$2");
        normalized = Regex.Replace(normalized, @"([a-z0-9])([A-Z])", "$1_$2");
        normalized = Regex.Replace(normalized, @"[^\p{L}\p{Nd}]+", "_");
        normalized = Regex.Replace(normalized, @"_+", "_");
        return normalized.Trim('_').ToLowerInvariant();
    }

    private static string ConvertToPascalCase(string value)
    {
        var snakeCaseName = ConvertToSnakeCase(value);
        return string.Concat(snakeCaseName
            .Split('_', StringSplitOptions.RemoveEmptyEntries)
            .Select(word => char.ToUpperInvariant(word[0]) + word[1..]));
    }

    private static string GetDisplayPath(string fullPath)
    {
        if (string.IsNullOrWhiteSpace(fullPath))
        {
            return "";
        }

        var pathParts = fullPath.Split(['\\', '/'], StringSplitOptions.RemoveEmptyEntries);
        var gameTaskIndex = Array.FindIndex(pathParts,
            part => string.Equals(part, "GameTask", StringComparison.OrdinalIgnoreCase));
        if (gameTaskIndex >= 0 && gameTaskIndex + 1 < pathParts.Length)
        {
            return string.Join(Path.DirectorySeparatorChar, pathParts.Skip(gameTaskIndex + 1));
        }

        // 找不到 GameTask 时保留最后三级目录和文件名，并提示前方路径已省略。
        const int directoryLevels = 3;
        var visiblePartCount = Math.Min(pathParts.Length, directoryLevels + 1);
        var visiblePath = string.Join(Path.DirectorySeparatorChar, pathParts.Skip(pathParts.Length - visiblePartCount));
        return visiblePartCount < pathParts.Length
            ? $"…{Path.DirectorySeparatorChar}{visiblePath}"
            : visiblePath;
    }

    private static System.Windows.Window? GetActiveWindow()
    {
        return Application.Current?.Windows.OfType<System.Windows.Window>().FirstOrDefault(window => window.IsActive)
               ?? Application.Current?.MainWindow;
    }

    private static void TrySetDialogInitialPath(VistaSaveFileDialog dialog, string path)
    {
        if (string.IsNullOrWhiteSpace(path))
        {
            return;
        }

        try
        {
            var fullPath = Path.GetFullPath(path.Trim());
            var directory = Path.GetDirectoryName(fullPath);
            if (!string.IsNullOrWhiteSpace(directory) && Directory.Exists(directory))
            {
                dialog.InitialDirectory = directory;
            }

            var fileName = Path.GetFileName(fullPath);
            if (!string.IsNullOrWhiteSpace(fileName))
            {
                dialog.FileName = fileName;
            }
        }
        catch
        {
            // 无效的历史路径不应影响重新选择文件。
        }
    }

    private static void ShowWarning(string message)
    {
        ThemedMessageBox.Show(
            message,
            "配置有误",
            MessageBoxButton.OK,
            ThemedMessageBox.MessageBoxIcon.Warning,
            MessageBoxResult.OK,
            GetActiveWindow());
    }

    public void Dispose()
    {
        if (_disposed)
        {
            return;
        }

        _disposed = true;
        _screenshot.Dispose();
        GC.SuppressFinalize(this);
    }
}
