using BetterGenshinImpact.Core.Config;
using BetterGenshinImpact.Core.Recognition;
using BetterGenshinImpact.Helpers.Extensions;
using BetterGenshinImpact.Service;
using BetterGenshinImpact.Service.Interface;
using BetterGenshinImpact.View.Windows;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Microsoft.Extensions.Logging;
using Ookii.Dialogs.Wpf;
using OpenCvSharp;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Windows;
using System.Windows.Media.Imaging;
using CvRect = OpenCvSharp.Rect;

namespace BetterGenshinImpact.ViewModel.Windows;

public partial class RecognitionTemplateEditorViewModel : ViewModel, IDisposable
{
    private readonly Mat _screenshot;
    private readonly RecognitionTemplateAssetService _assetService;
    private readonly DevConfig _devConfig;
    private readonly ILogger<RecognitionTemplateEditorViewModel> _logger = App.GetLogger<RecognitionTemplateEditorViewModel>();
    private bool _disposed;
    private string _lastAutoGeneratedObjectName = "";

    public event Action? RequestClose;

    public IReadOnlyList<TemplateMatchModes> TemplateMatchModeItems { get; } = Enum.GetValues<TemplateMatchModes>();

    public IReadOnlyList<SearchAnchorMode> SearchAnchorModeItems { get; } = Enum.GetValues<SearchAnchorMode>();

    public int CanvasWidth => _screenshot.Width;

    public int CanvasHeight => _screenshot.Height;

    public string ReferenceSizeText => $"{CanvasWidth} x {CanvasHeight}";

    public string OutputImagePath => RecognitionTemplateAssetService.GetImageOutputPath(AssetsRootPath, TemplateFileNameWithExtension);

    public string OutputImageDisplayPath => GetDisplayPath(OutputImagePath);

    private string TemplateFileNameWithExtension => string.IsNullOrWhiteSpace(TemplateFileName)
        ? ""
        : ConvertToSnakeCase(TemplateFileName) + ".png";

    [ObservableProperty]
    private WriteableBitmap _screenshotImage;

    [ObservableProperty]
    private WriteableBitmap? _croppedPreviewImage;

    [ObservableProperty]
    private string _recognitionJsonPath;

    [ObservableProperty]
    private string _assetsRootPath;

    [ObservableProperty]
    private string _objectName = "";

    [ObservableProperty]
    private string _templateFileName = "";

    [ObservableProperty]
    private int _selectionX;

    [ObservableProperty]
    private int _selectionY;

    [ObservableProperty]
    private int _selectionWidth;

    [ObservableProperty]
    private int _selectionHeight;

    [ObservableProperty]
    private double _threshold = RecognitionTemplateDraft.DefaultThreshold;

    [ObservableProperty]
    private TemplateMatchModes _templateMatchMode = RecognitionTemplateDraft.DefaultTemplateMatchMode;

    [ObservableProperty]
    private bool _use3Channels;

    [ObservableProperty]
    private bool _useMask;

    [ObservableProperty]
    private string _maskColor = RecognitionTemplateDraft.DefaultMaskColor;

    [ObservableProperty]
    private bool _useBinaryMatch;

    [ObservableProperty]
    private int _binaryThreshold = RecognitionTemplateDraft.DefaultBinaryThreshold;

    [ObservableProperty]
    private int _maxMatchCount = RecognitionTemplateDraft.DefaultMaxMatchCount;

    [ObservableProperty]
    private bool _drawOnWindow;

    [ObservableProperty]
    private SearchAnchorMode _searchAnchorMode = RecognitionTemplateDraft.DefaultSearchAnchorMode;

    [ObservableProperty]
    private int _searchExpandWidth = RecognitionTemplateDraft.DefaultSearchExpand;

    [ObservableProperty]
    private int _searchExpandHeight = RecognitionTemplateDraft.DefaultSearchExpand;

    [ObservableProperty]
    private double _zoomScale = 0.5;

    [ObservableProperty]
    private int _fitRequestToken;

    public RecognitionTemplateEditorViewModel(
        Mat screenshot,
        RecognitionTemplateAssetService assetService,
        IConfigService configService,
        string initialTemplateName = "")
    {
        _screenshot = screenshot ?? throw new ArgumentNullException(nameof(screenshot));
        _assetService = assetService;
        _devConfig = configService.Get().DevConfig;
        _recognitionJsonPath = _devConfig.RecognitionJsonPath;
        _assetsRootPath = _devConfig.RecognitionAssetsRootPath;
        _screenshotImage = screenshot.ToWriteableBitmap();
        if (!string.IsNullOrWhiteSpace(initialTemplateName))
        {
            TemplateFileName = initialTemplateName;
        }
    }

    [RelayCommand]
    private void BrowseRecognitionJson()
    {
        var dialog = new VistaSaveFileDialog
        {
            Title = "选择或创建 Recognition.json",
            Filter = "Recognition JSON (*.json)|*.json|所有文件 (*.*)|*.*",
            DefaultExt = ".json",
            AddExtension = true,
            OverwritePrompt = false,
            FileName = "Recognition.json"
        };

        TrySetDialogInitialPath(dialog, RecognitionJsonPath);
        if (dialog.ShowDialog(GetActiveWindow()) != true)
        {
            return;
        }

        RecognitionJsonPath = dialog.FileName;
        if (string.IsNullOrWhiteSpace(AssetsRootPath))
        {
            AssetsRootPath = Path.GetDirectoryName(dialog.FileName) ?? "";
        }
    }

    [RelayCommand]
    private void BrowseAssetsRoot()
    {
        var dialog = new VistaFolderBrowserDialog
        {
            Description = "选择输出文件夹（Recognition.json 写入此目录，图片写入 1920x1080 子目录）",
            UseDescriptionForTitle = true,
            SelectedPath = Directory.Exists(AssetsRootPath) ? AssetsRootPath : ""
        };
        if (dialog.ShowDialog(GetActiveWindow()) != true)
        {
            return;
        }

        AssetsRootPath = dialog.SelectedPath;
        RecognitionJsonPath = Path.Combine(dialog.SelectedPath, "Recognition.json");
    }

    [RelayCommand]
    private void FitImage()
    {
        FitRequestToken++;
    }

    [RelayCommand]
    private void Save()
    {
        try
        {
            NormalizeTemplateFileName();
            var draft = new RecognitionTemplateDraft
            {
                JsonPath = RecognitionJsonPath,
                AssetsRootPath = AssetsRootPath,
                ObjectName = ObjectName,
                TemplateFileName = TemplateFileNameWithExtension,
                Selection = new CvRect(SelectionX, SelectionY, SelectionWidth, SelectionHeight),
                ReferenceWidth = CanvasWidth,
                ReferenceHeight = CanvasHeight,
                Threshold = Threshold,
                TemplateMatchMode = TemplateMatchMode,
                Use3Channels = Use3Channels,
                UseMask = UseMask,
                MaskColor = MaskColor,
                UseBinaryMatch = UseBinaryMatch,
                BinaryThreshold = BinaryThreshold,
                MaxMatchCount = MaxMatchCount,
                DrawOnWindow = DrawOnWindow,
                SearchAnchorMode = SearchAnchorMode,
                SearchExpandWidth = SearchExpandWidth,
                SearchExpandHeight = SearchExpandHeight
            };

            var plan = _assetService.Prepare(draft);
            if (plan.Conflicts.Count > 0)
            {
                var conflictText = string.Join(Environment.NewLine, plan.Conflicts.Select(conflict => $"• {conflict}"));
                var result = ThemedMessageBox.Show(
                    $"检测到以下冲突：{Environment.NewLine}{Environment.NewLine}{conflictText}{Environment.NewLine}{Environment.NewLine}是否覆盖并继续保存？",
                    "确认覆盖模板素材",
                    MessageBoxButton.YesNo,
                    ThemedMessageBox.MessageBoxIcon.Warning,
                    MessageBoxResult.No,
                    GetActiveWindow());
                if (result != MessageBoxResult.Yes)
                {
                    return;
                }
            }

            _assetService.Commit(plan, _screenshot);
            _devConfig.RecognitionJsonPath = plan.JsonPath;
            _devConfig.RecognitionAssetsRootPath = Path.GetFullPath(AssetsRootPath.Trim());

            ThemedMessageBox.Show(
                $"模板素材已保存。{Environment.NewLine}{Environment.NewLine}配置：{plan.JsonPath}{Environment.NewLine}图片：{plan.ImagePath}",
                "保存成功",
                MessageBoxButton.OK,
                ThemedMessageBox.MessageBoxIcon.Success,
                MessageBoxResult.OK,
                GetActiveWindow());
            RequestClose?.Invoke();
        }
        catch (ArgumentException ex)
        {
            ShowWarning(ex.Message);
        }
        catch (InvalidOperationException ex)
        {
            ShowWarning(ex.Message);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "保存 Recognition 模板素材失败");
            ThemedMessageBox.Show(
                $"保存 Recognition 模板素材失败：{ex.Message}",
                "保存失败",
                MessageBoxButton.OK,
                ThemedMessageBox.MessageBoxIcon.Error,
                MessageBoxResult.OK,
                GetActiveWindow());
        }
    }

    [RelayCommand]
    private void Cancel()
    {
        RequestClose?.Invoke();
    }

    [RelayCommand]
    private void NormalizeTemplateFileName()
    {
        var normalizedName = ConvertToSnakeCase(TemplateFileName);
        TemplateFileName = normalizedName;
    }

    partial void OnRecognitionJsonPathChanged(string value)
    {
        OnPropertyChanged(nameof(OutputImagePath));
    }

    partial void OnAssetsRootPathChanged(string value)
    {
        OnPropertyChanged(nameof(OutputImagePath));
        OnPropertyChanged(nameof(OutputImageDisplayPath));
    }

    partial void OnTemplateFileNameChanged(string value)
    {
        OnPropertyChanged(nameof(OutputImagePath));
        OnPropertyChanged(nameof(OutputImageDisplayPath));
        UpdateAutoGeneratedObjectName(value);
    }

    partial void OnSelectionXChanged(int value) => UpdateCroppedPreview();

    partial void OnSelectionYChanged(int value) => UpdateCroppedPreview();

    partial void OnSelectionWidthChanged(int value) => UpdateCroppedPreview();

    partial void OnSelectionHeightChanged(int value) => UpdateCroppedPreview();

    private void UpdateCroppedPreview()
    {
        var selection = new CvRect(SelectionX, SelectionY, SelectionWidth, SelectionHeight);
        if (selection.Width <= 0 || selection.Height <= 0
            || selection.X < 0 || selection.Y < 0
            || selection.Right > CanvasWidth || selection.Bottom > CanvasHeight)
        {
            CroppedPreviewImage = null;
            return;
        }

        using var cropped = new Mat(_screenshot, selection);
        CroppedPreviewImage = cropped.ToWriteableBitmap();
    }

    private void UpdateAutoGeneratedObjectName(string templateFileName)
    {
        var generatedObjectName = ConvertToPascalCase(templateFileName);
        if (string.IsNullOrWhiteSpace(ObjectName)
            || string.Equals(ObjectName, _lastAutoGeneratedObjectName, StringComparison.Ordinal))
        {
            ObjectName = generatedObjectName;
        }

        _lastAutoGeneratedObjectName = generatedObjectName;
    }

    private static string ConvertToSnakeCase(string value)
    {
        var normalized = value.Trim();
        if (normalized.EndsWith(".png", StringComparison.OrdinalIgnoreCase))
        {
            normalized = normalized[..^4];
        }

        // 兼容 PascalCase、camelCase、连续大写缩写以及空格/连字符等分隔符。
        normalized = Regex.Replace(normalized, @"([A-Z]+)([A-Z][a-z])", "$1_$2");
        normalized = Regex.Replace(normalized, @"([a-z0-9])([A-Z])", "$1_$2");
        normalized = Regex.Replace(normalized, @"[^\p{L}\p{Nd}]+", "_");
        normalized = Regex.Replace(normalized, @"_+", "_");
        return normalized.Trim('_').ToLowerInvariant();
    }

    private static string ConvertToPascalCase(string value)
    {
        var snakeCaseName = ConvertToSnakeCase(value);
        return string.Concat(snakeCaseName
            .Split('_', StringSplitOptions.RemoveEmptyEntries)
            .Select(word => char.ToUpperInvariant(word[0]) + word[1..]));
    }

    private static string GetDisplayPath(string fullPath)
    {
        if (string.IsNullOrWhiteSpace(fullPath))
        {
            return "";
        }

        var pathParts = fullPath.Split(['\\', '/'], StringSplitOptions.RemoveEmptyEntries);
        var gameTaskIndex = Array.FindIndex(pathParts,
            part => string.Equals(part, "GameTask", StringComparison.OrdinalIgnoreCase));
        if (gameTaskIndex >= 0 && gameTaskIndex + 1 < pathParts.Length)
        {
            return string.Join(Path.DirectorySeparatorChar, pathParts.Skip(gameTaskIndex + 1));
        }

        // 找不到 GameTask 时保留最后三级目录和文件名，并提示前方路径已省略。
        const int directoryLevels = 3;
        var visiblePartCount = Math.Min(pathParts.Length, directoryLevels + 1);
        var visiblePath = string.Join(Path.DirectorySeparatorChar, pathParts.Skip(pathParts.Length - visiblePartCount));
        return visiblePartCount < pathParts.Length
            ? $"…{Path.DirectorySeparatorChar}{visiblePath}"
            : visiblePath;
    }

    private static System.Windows.Window? GetActiveWindow()
    {
        return Application.Current?.Windows.OfType<System.Windows.Window>().FirstOrDefault(window => window.IsActive)
               ?? Application.Current?.MainWindow;
    }

    private static void TrySetDialogInitialPath(VistaSaveFileDialog dialog, string path)
    {
        if (string.IsNullOrWhiteSpace(path))
        {
            return;
        }

        try
        {
            var fullPath = Path.GetFullPath(path.Trim());
            var directory = Path.GetDirectoryName(fullPath);
            if (!string.IsNullOrWhiteSpace(directory) && Directory.Exists(directory))
            {
                dialog.InitialDirectory = directory;
            }

            var fileName = Path.GetFileName(fullPath);
            if (!string.IsNullOrWhiteSpace(fileName))
            {
                dialog.FileName = fileName;
            }
        }
        catch
        {
            // 无效的历史路径不应影响重新选择文件。
        }
    }

    private static void ShowWarning(string message)
    {
        ThemedMessageBox.Show(
            message,
            "配置有误",
            MessageBoxButton.OK,
            ThemedMessageBox.MessageBoxIcon.Warning,
            MessageBoxResult.OK,
            GetActiveWindow());
    }

    public void Dispose()
    {
        if (_disposed)
        {
            return;
        }

        _disposed = true;
        _screenshot.Dispose();
        GC.SuppressFinalize(this);
    }
}
